version: '2'
services:
  chefmateserver:
    build:
      context: .
      dockerfile: Dockerfile-chefmateserver
    ports:
      - "8080:8080"
    volumes:
      - apistore:/api
    command: java -jar chefmateserver-1.1.jar -p 8080

  apiadapter:
    # TODO: Replace with dockerfile of apiadapter
    image: ubuntu
    volumes_from:
      - chefmateserver
    links:
      - chefmateserver
    # TODO: Ports needed for REST?
    # TODO: I think that isn't needed if already defined in Dockerfile
    environment:
      # TODO: Update ASAP
      API_HOST: localhost
      API_PORT: 8080
      API_PROTO_PATH: /api/main.proto
    # TODO: Remove the check if proto is available ASAP and replace with apiadapter start routine
    command: ls -LR /api

volumes:
  apistore:
